# This is a basic workflow to help you get started with Actions

name: Scrape

# Allow the action to write to the repository
permissions:
  contents: write

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  
  # Triggers workflow on schedule. Pick your cron schedule https://crontab.guru/
  schedule:
  - cron: "0 2 * * 1-5"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  scrape:
    name: Scrape
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.15.1'
          cache: 'yarn'
      - run: yarn install

      # Execute scrape
      - run: yarn scrape

      # Configure dummy git account. You can replace with your own credentials
      - run: git config user.name github-actions
      - run: git config user.email github-actions@github.com

      # Save the data in the repository through git-commit
      - run: |
          git add .
          git commit --allow-empty -m "scrape via worklfow run"
          git push origin master


